export const ScreenKey = {
  SplashScreen: 'splashScreen',
  MainTab: 'mainTab',
  ListCourses: 'listCourses',
  CourseDetail: 'courseDetail',
  Home: 'Home',
  Downloads: 'Downloads',
  Browse: 'Browse',
  Search: 'Search',
  AuthenticationStackScreens: 'authenticationStackScreens',
  LoginScreen: 'loginScreen',
  RegisterScreen: 'registerScreen',
  ForgetPasswordScreen: 'forgetPasswordScreen',
  SettingScreen: 'settingScreen',
  SettingStackScreens: 'settingStackScreens',
  EditProfile: 'editProfile',
  ManagementAccountStackScreens: 'managementAccountStackScreens',
  Profile: 'Profile',
};
